// AUTO-GENERATED BY npm run generate:wrappers. DO NOT EDIT MANUALLY.
import { defineComponent, h, type PropType } from "vue";

import type {
  AutocompleteSuggestion,
  ButtonGroupOrientation,
  ButtonType,
  ButtonVariant,
  ChipTone,
  CommandPaletteCommand,
  DataTableColumn,
  DataTableRow,
  DataTableSortDirection,
  FilterBuilderField,
  LucideIconName,
  ProviderTheme,
  ProviderThemeTokens,
  SegmentedControlOption,
  SkeletonVariant,
  SplitterOrientation,
  StackAlign,
  StackDirection,
  StackGap,
  StackJustify,
  StatCardTone,
  StepperOrientation,
  StepperStep,
  TagTone,
  ToastPlacement,
  ToolbarOrientation
} from "cindor-ui-core";
export { clearToasts, dismissToast, ensureToastRegion, showToast } from "cindor-ui-core";
import "cindor-ui-core/register";

type InputHost = HTMLElement & { value: string };
type CheckboxHost = HTMLElement & { checked: boolean };
type SelectHost = HTMLElement & { value: string };
type OpenHost = HTMLElement & { open: boolean };
type FileInputHost = HTMLElement & { files: FileList | null };
type PageHost = HTMLElement & { currentPage: number };
type SearchQueryHost = HTMLElement & { searchQuery: string };

export const CindorButton = defineComponent({
  name: "CindorButton",
  props: {
    disabled: { type: Boolean, default: false },
    iconOnly: { type: Boolean, default: false },
    type: { type: String as PropType<ButtonType>, default: "button" },
    variant: { type: String as PropType<ButtonVariant>, default: "solid" }
  },
  setup(props, { attrs, slots }) {
    return () =>
          h(
            "cindor-button",
            {
              ...attrs,
              disabled: props.disabled || undefined,
              iconOnly: props.iconOnly || undefined,
              type: props.type,
              variant: props.variant,
            },
            slots
          );
  }
});

export const CindorButtonGroup = defineComponent({
  name: "CindorButtonGroup",
  props: {
    attached: { type: Boolean, default: false },
    orientation: { type: String as PropType<ButtonGroupOrientation>, default: "horizontal" }
  },
  setup(props, { attrs, slots }) {
    return () =>
          h(
            "cindor-button-group",
            {
              ...attrs,
              attached: props.attached || undefined,
              orientation: props.orientation,
            },
            slots.default?.()
          );
  }
});

export const CindorChip = defineComponent({
  name: "CindorChip",
  props: {
    tone: { type: String as PropType<ChipTone>, default: "neutral" }
  },
  setup(props, { attrs, slots }) {
    return () =>
          h(
            "cindor-chip",
            {
              ...attrs,
              tone: props.tone,
            },
            slots.default?.()
          );
  }
});

export const CindorTag = defineComponent({
  name: "CindorTag",
  props: {
    dismissible: { type: Boolean, default: false },
    removeLabel: { type: String, default: "Remove tag" },
    tone: { type: String as PropType<TagTone>, default: "accent" }
  },
  emits: ["remove"],
  setup(props, { attrs, emit, slots }) {
    const handleRemove = (event: Event) => {
      emit("remove", event);
    };
    return () =>
          h(
            "cindor-tag",
            {
              ...attrs,
              dismissible: props.dismissible || undefined,
              "remove-label": props.removeLabel,
              tone: props.tone,
              onRemove: handleRemove,
            },
            slots.default?.()
          );
  }
});

export const CindorIconButton = defineComponent({
  name: "CindorIconButton",
  props: {
    disabled: { type: Boolean, default: false },
    label: { type: String, default: "" },
    name: { type: String as PropType<LucideIconName | string>, default: "" },
    size: { type: Number, default: 16 },
    strokeWidth: { type: Number, default: 2 },
    type: { type: String as PropType<ButtonType>, default: "button" }
  },
  setup(props, { attrs }) {
    return () =>
          h("cindor-icon-button", {
              ...attrs,
              disabled: props.disabled || undefined,
              label: props.label || undefined,
              name: props.name,
              size: props.size,
              "stroke-width": props.strokeWidth,
              type: props.type,
          });
  }
});

export const CindorCard = defineComponent({
  name: "CindorCard",
  setup(_, { attrs, slots }) {
    return () =>
          h(
            "cindor-card",
            {
              ...attrs,
            },
            slots.default?.()
          );
  }
});

export const CindorCalendar = defineComponent({
  name: "CindorCalendar",
  props: {
    disabled: { type: Boolean, default: false },
    endValue: { type: String, default: "" },
    max: { type: String, default: "" },
    min: { type: String, default: "" },
    month: { type: String, default: "" },
    modelValue: { type: String, default: "" },
    name: { type: String, default: "" },
    range: { type: Boolean, default: false },
    required: { type: Boolean, default: false },
    startValue: { type: String, default: "" }
  },
  emits: ["update:modelValue", "input", "change"],
  setup(props, { attrs, emit }) {
    const handleInput = (event: Event) => {
      const target = event.currentTarget as InputHost;
      emit("update:modelValue", target.value);
      emit("input", event);
    };

    const handleChange = (event: Event) => {
      const target = event.currentTarget as InputHost;
      emit("update:modelValue", target.value);
      emit("change", event);
    };
    return () =>
          h("cindor-calendar", {
              ...attrs,
              disabled: props.disabled || undefined,
              "end-value": props.endValue || undefined,
              max: props.max || undefined,
              min: props.min || undefined,
              month: props.month || undefined,
              value: props.modelValue,
              name: props.name || undefined,
              range: props.range || undefined,
              required: props.required || undefined,
              "start-value": props.startValue || undefined,
              onInput: handleInput,
              onChange: handleChange,
          });
  }
});

export const CindorBadge = defineComponent({
  name: "CindorBadge",
  props: {
    tone: { type: String as PropType<"neutral" | "accent" | "success">, default: "neutral" }
  },
  setup(props, { attrs, slots }) {
    return () =>
          h(
            "cindor-badge",
            {
              ...attrs,
              tone: props.tone,
            },
            slots.default?.()
          );
  }
});

export const CindorDivider = defineComponent({
  name: "CindorDivider",
  setup(_, { attrs }) {
    return () =>
          h("cindor-divider", {
              ...attrs,
          });
  }
});

export const CindorProvider = defineComponent({
  name: "CindorProvider",
  props: {
    darkThemeTokens: { type: Object as PropType<ProviderThemeTokens>, default: () => ({}) },
    lightThemeTokens: { type: Object as PropType<ProviderThemeTokens>, default: () => ({}) },
    primaryColor: { type: String, default: "" },
    themeTokens: { type: Object as PropType<ProviderThemeTokens>, default: () => ({}) },
    theme: { type: String as PropType<ProviderTheme>, default: "inherit" }
  },
  setup(props, { attrs, slots }) {
    return () =>
          h(
            "cindor-provider",
            {
              ...attrs,
              darkThemeTokens: props.darkThemeTokens,
              lightThemeTokens: props.lightThemeTokens,
              "primary-color": props.primaryColor,
              themeTokens: props.themeTokens,
              theme: props.theme,
            },
            slots.default?.()
          );
  }
});

export const CindorSpinner = defineComponent({
  name: "CindorSpinner",
  setup(_, { attrs }) {
    return () =>
          h("cindor-spinner", {
              ...attrs,
          });
  }
});

export const CindorAlert = defineComponent({
  name: "CindorAlert",
  props: {
    tone: { type: String as PropType<"info" | "success" | "warning" | "danger">, default: "info" }
  },
  setup(props, { attrs, slots }) {
    return () =>
          h(
            "cindor-alert",
            {
              ...attrs,
              tone: props.tone,
            },
            slots.default?.()
          );
  }
});

export const CindorActivityFeed = defineComponent({
  name: "CindorActivityFeed",
  setup(_, { attrs, slots }) {
    return () =>
          h(
            "cindor-activity-feed",
            {
              ...attrs,
            },
            slots.default?.()
          );
  }
});

export const CindorActivityItem = defineComponent({
  name: "CindorActivityItem",
  props: {
    unread: { type: Boolean, default: false }
  },
  setup(props, { attrs, slots }) {
    return () =>
          h(
            "cindor-activity-item",
            {
              ...attrs,
              unread: props.unread || undefined,
            },
            slots
          );
  }
});

export const CindorAutocomplete = defineComponent({
  name: "CindorAutocomplete",
  props: {
    disabled: { type: Boolean, default: false },
    emptyMessage: { type: String, default: "No matching suggestions." },
    loading: { type: Boolean, default: false },
    modelValue: { type: String, default: "" },
    name: { type: String, default: "" },
    open: { type: Boolean, default: false },
    placeholder: { type: String, default: "" },
    required: { type: Boolean, default: false },
    suggestions: { type: Array as PropType<AutocompleteSuggestion[]>, default: () => [] }
  },
  emits: ["update:modelValue", "input", "change", "suggestion-select"],
  setup(props, { attrs, emit }) {
    const handleInput = (event: Event) => {
      const target = event.currentTarget as InputHost;
      emit("update:modelValue", target.value);
      emit("input", event);
    };

    const handleChange = (event: Event) => {
      const target = event.currentTarget as InputHost;
      emit("update:modelValue", target.value);
      emit("change", event);
    };

    const handleSuggestionSelect = (event: Event) => {
      emit("suggestion-select", event);
    };
    return () =>
          h("cindor-autocomplete", {
              ...attrs,
              disabled: props.disabled || undefined,
              "empty-message": props.emptyMessage,
              loading: props.loading || undefined,
              value: props.modelValue,
              name: props.name || undefined,
              open: props.open || undefined,
              placeholder: props.placeholder || undefined,
              required: props.required || undefined,
              suggestions: props.suggestions,
              onInput: handleInput,
              onChange: handleChange,
              onSuggestionSelect: handleSuggestionSelect,
          });
  }
});

export const CindorAvatar = defineComponent({
  name: "CindorAvatar",
  props: {
    alt: { type: String, default: "" },
    name: { type: String, default: "" },
    src: { type: String, default: "" }
  },
  setup(props, { attrs }) {
    return () =>
          h("cindor-avatar", {
              ...attrs,
              alt: props.alt || undefined,
              name: props.name || undefined,
              src: props.src || undefined,
          });
  }
});

export const CindorProgress = defineComponent({
  name: "CindorProgress",
  props: {
    max: { type: Number, default: 100 },
    value: { type: Number, default: 0 }
  },
  setup(props, { attrs, slots }) {
    return () =>
          h(
            "cindor-progress",
            {
              ...attrs,
              max: props.max,
              value: props.value,
            },
            slots.default?.()
          );
  }
});

export const CindorMeter = defineComponent({
  name: "CindorMeter",
  props: {
    high: { type: Number, default: 100 },
    low: { type: Number, default: 0 },
    max: { type: Number, default: 100 },
    min: { type: Number, default: 0 },
    optimum: { type: Number, default: 100 },
    value: { type: Number, default: 0 }
  },
  setup(props, { attrs, slots }) {
    return () =>
          h(
            "cindor-meter",
            {
              ...attrs,
              high: props.high,
              low: props.low,
              max: props.max,
              min: props.min,
              optimum: props.optimum,
              value: props.value,
            },
            slots.default?.()
          );
  }
});

export const CindorBreadcrumbs = defineComponent({
  name: "CindorBreadcrumbs",
  setup(_, { attrs, slots }) {
    return () =>
          h(
            "cindor-breadcrumbs",
            {
              ...attrs,
            },
            slots.default?.()
          );
  }
});

export const CindorSkeleton = defineComponent({
  name: "CindorSkeleton",
  props: {
    variant: { type: String as PropType<SkeletonVariant>, default: "line" }
  },
  setup(props, { attrs }) {
    return () =>
          h("cindor-skeleton", {
              ...attrs,
              variant: props.variant,
          });
  }
});

export const CindorStepper = defineComponent({
  name: "CindorStepper",
  props: {
    disabled: { type: Boolean, default: false },
    interactive: { type: Boolean, default: false },
    orientation: { type: String as PropType<StepperOrientation>, default: "horizontal" },
    steps: { type: Array as PropType<StepperStep[]>, default: () => [] },
    modelValue: { type: String, default: "" }
  },
  emits: ["update:modelValue", "input", "change"],
  setup(props, { attrs, emit }) {
    const handleInput = (event: Event) => {
      const target = event.currentTarget as InputHost;
      emit("update:modelValue", target.value);
      emit("input", event);
    };

    const handleChange = (event: Event) => {
      const target = event.currentTarget as InputHost;
      emit("update:modelValue", target.value);
      emit("change", event);
    };
    return () =>
          h("cindor-stepper", {
              ...attrs,
              disabled: props.disabled || undefined,
              interactive: props.interactive || undefined,
              orientation: props.orientation,
              steps: props.steps,
              value: props.modelValue,
              onInput: handleInput,
              onChange: handleChange,
          });
  }
});

export const CindorLink = defineComponent({
  name: "CindorLink",
  props: {
    download: { type: String, default: "" },
    href: { type: String, default: "" },
    rel: { type: String, default: "" },
    target: { type: String, default: "" }
  },
  setup(props, { attrs, slots }) {
    return () =>
          h(
            "cindor-link",
            {
              ...attrs,
              download: props.download || undefined,
              href: props.href || undefined,
              rel: props.rel || undefined,
              target: props.target || undefined,
            },
            slots.default?.()
          );
  }
});

export const CindorFieldset = defineComponent({
  name: "CindorFieldset",
  props: {
    disabled: { type: Boolean, default: false },
    legend: { type: String, default: "" }
  },
  setup(props, { attrs, slots }) {
    return () =>
          h(
            "cindor-fieldset",
            {
              ...attrs,
              disabled: props.disabled || undefined,
              legend: props.legend || undefined,
            },
            slots
          );
  }
});

export const CindorForm = defineComponent({
  name: "CindorForm",
  props: {
    description: { type: String, default: "" },
    error: { type: String, default: "" },
    submitting: { type: Boolean, default: false },
    submittingLabel: { type: String, default: "Submitting…" },
    success: { type: String, default: "" },
    validateOnSubmit: { type: Boolean, default: true }
  },
  emits: ["reset", "submit"],
  setup(props, { attrs, emit, slots }) {
    const handleReset = (event: Event) => {
      emit("reset", event);
    };

    const handleSubmit = (event: Event) => {
      emit("submit", event);
    };
    return () =>
          h(
            "cindor-form",
            {
              ...attrs,
              description: props.description || undefined,
              error: props.error || undefined,
              submitting: props.submitting || undefined,
              "submitting-label": props.submittingLabel,
              success: props.success || undefined,
              "validate-on-submit": props.validateOnSubmit || undefined,
              onReset: handleReset,
              onSubmit: handleSubmit,
            },
            slots.default?.()
          );
  }
});

export const CindorFormField = defineComponent({
  name: "CindorFormField",
  props: {
    description: { type: String, default: "" },
    error: { type: String, default: "" },
    label: { type: String, default: "" },
    required: { type: Boolean, default: false }
  },
  setup(props, { attrs, slots }) {
    return () =>
          h(
            "cindor-form-field",
            {
              ...attrs,
              description: props.description || undefined,
              error: props.error || undefined,
              label: props.label || undefined,
              required: props.required || undefined,
            },
            slots
          );
  }
});

export const CindorFormRow = defineComponent({
  name: "CindorFormRow",
  props: {
    columns: { type: Number, default: 2 }
  },
  setup(props, { attrs, slots }) {
    return () =>
          h(
            "cindor-form-row",
            {
              ...attrs,
              columns: props.columns,
            },
            slots.default?.()
          );
  }
});

export const CindorHelperText = defineComponent({
  name: "CindorHelperText",
  setup(_, { attrs, slots }) {
    return () =>
          h(
            "cindor-helper-text",
            {
              ...attrs,
            },
            slots.default?.()
          );
  }
});

export const CindorErrorText = defineComponent({
  name: "CindorErrorText",
  setup(_, { attrs, slots }) {
    return () =>
          h(
            "cindor-error-text",
            {
              ...attrs,
            },
            slots.default?.()
          );
  }
});

export const CindorRange = defineComponent({
  name: "CindorRange",
  props: {
    disabled: { type: Boolean, default: false },
    max: { type: Number, default: 100 },
    min: { type: Number, default: 0 },
    name: { type: String, default: "" },
    required: { type: Boolean, default: false },
    step: { type: Number, default: 1 },
    modelValue: { type: Number, default: 0 }
  },
  emits: ["update:modelValue", "input", "change"],
  setup(props, { attrs, emit }) {
    const handleInput = (event: Event) => {
      const target = event.currentTarget as InputHost;
      emit("update:modelValue", Number(target.value));
      emit("input", event);
    };

    const handleChange = (event: Event) => {
      const target = event.currentTarget as InputHost;
      emit("update:modelValue", Number(target.value));
      emit("change", event);
    };
    return () =>
          h("cindor-range", {
              ...attrs,
              disabled: props.disabled || undefined,
              max: props.max,
              min: props.min,
              name: props.name || undefined,
              required: props.required || undefined,
              step: props.step,
              value: props.modelValue,
              onInput: handleInput,
              onChange: handleChange,
          });
  }
});

export const CindorFileInput = defineComponent({
  name: "CindorFileInput",
  props: {
    accept: { type: String, default: "" },
    disabled: { type: Boolean, default: false },
    multiple: { type: Boolean, default: false },
    name: { type: String, default: "" },
    required: { type: Boolean, default: false }
  },
  emits: ["update:files", "input", "change"],
  setup(props, { attrs, emit }) {
    const handleInput = (event: Event) => {
      const target = event.currentTarget as FileInputHost;
      emit("update:files", target.files);
      emit("input", event);
    };

    const handleChange = (event: Event) => {
      const target = event.currentTarget as FileInputHost;
      emit("update:files", target.files);
      emit("change", event);
    };
    return () =>
          h("cindor-file-input", {
              ...attrs,
              accept: props.accept || undefined,
              disabled: props.disabled || undefined,
              multiple: props.multiple || undefined,
              name: props.name || undefined,
              required: props.required || undefined,
              onInput: handleInput,
              onChange: handleChange,
          });
  }
});

export const CindorFilterBuilder = defineComponent({
  name: "CindorFilterBuilder",
  props: {
    disabled: { type: Boolean, default: false },
    fields: { type: Array as PropType<FilterBuilderField[]>, default: () => [] },
    name: { type: String, default: "" },
    modelValue: { type: String, default: "" }
  },
  emits: ["update:modelValue", "input", "change"],
  setup(props, { attrs, emit }) {
    const handleInput = (event: Event) => {
      const target = event.currentTarget as InputHost;
      emit("update:modelValue", target.value);
      emit("input", event);
    };

    const handleChange = (event: Event) => {
      const target = event.currentTarget as InputHost;
      emit("update:modelValue", target.value);
      emit("change", event);
    };
    return () =>
          h("cindor-filter-builder", {
              ...attrs,
              disabled: props.disabled || undefined,
              fields: props.fields,
              name: props.name || undefined,
              value: props.modelValue,
              onInput: handleInput,
              onChange: handleChange,
          });
  }
});

export const CindorPagination = defineComponent({
  name: "CindorPagination",
  props: {
    currentPage: { type: Number, default: 1 },
    maxVisiblePages: { type: Number, default: 5 },
    totalPages: { type: Number, default: 1 }
  },
  emits: ["update:currentPage", "change"],
  setup(props, { attrs, emit }) {
    const handleChange = (event: Event) => {
      const target = event.currentTarget as PageHost;
      emit("update:currentPage", target.currentPage);
      emit("change", event);
    };
    return () =>
          h("cindor-pagination", {
              ...attrs,
              currentPage: props.currentPage,
              maxVisiblePages: props.maxVisiblePages,
              totalPages: props.totalPages,
              onChange: handleChange,
          });
  }
});

export const CindorPageHeader = defineComponent({
  name: "CindorPageHeader",
  props: {
    description: { type: String, default: "" },
    eyebrow: { type: String, default: "" },
    title: { type: String, default: "" }
  },
  setup(props, { attrs, slots }) {
    return () =>
          h(
            "cindor-page-header",
            {
              ...attrs,
              description: props.description || undefined,
              eyebrow: props.eyebrow || undefined,
              title: props.title || undefined,
            },
            slots
          );
  }
});

export const CindorPanelInspector = defineComponent({
  name: "CindorPanelInspector",
  props: {
    description: { type: String, default: "" },
    sticky: { type: Boolean, default: false },
    title: { type: String, default: "" }
  },
  setup(props, { attrs, slots }) {
    return () =>
          h(
            "cindor-panel-inspector",
            {
              ...attrs,
              description: props.description || undefined,
              sticky: props.sticky || undefined,
              title: props.title || undefined,
            },
            slots
          );
  }
});

export const CindorDataTable = defineComponent({
  name: "CindorDataTable",
  props: {
    caption: { type: String, default: "" },
    columns: { type: Array as PropType<DataTableColumn[]>, default: () => [] },
    currentPage: { type: Number, default: 1 },
    emptyMessage: { type: String, default: "No rows to display." },
    loading: { type: Boolean, default: false },
    pageSize: { type: Number, default: 10 },
    rows: { type: Array as PropType<DataTableRow[]>, default: () => [] },
    searchable: { type: Boolean, default: false },
    searchLabel: { type: String, default: "Search rows" },
    searchPlaceholder: { type: String, default: "Search rows" },
    searchQuery: { type: String, default: "" },
    sortDirection: { type: String as PropType<DataTableSortDirection>, default: "ascending" },
    sortKey: { type: String, default: "" }
  },
  emits: ["cell-edit", "update:currentPage", "page-change", "row-action", "update:searchQuery", "search-change"],
  setup(props, { attrs, emit }) {
    const handleCellEdit = (event: Event) => {
      emit("cell-edit", event);
    };

    const handlePageChange = (event: Event) => {
      const target = event.currentTarget as PageHost;
      emit("update:currentPage", target.currentPage);
      emit("page-change", event);
    };

    const handleRowAction = (event: Event) => {
      emit("row-action", event);
    };

    const handleSearchChange = (event: Event) => {
      const target = event.currentTarget as SearchQueryHost;
      emit("update:searchQuery", target.searchQuery);
      emit("search-change", event);
    };
    return () =>
          h("cindor-data-table", {
              ...attrs,
              caption: props.caption || undefined,
              columns: props.columns,
              currentPage: props.currentPage,
              emptyMessage: props.emptyMessage,
              loading: props.loading || undefined,
              pageSize: props.pageSize,
              rows: props.rows,
              searchable: props.searchable || undefined,
              searchLabel: props.searchLabel,
              searchPlaceholder: props.searchPlaceholder,
              searchQuery: props.searchQuery || undefined,
              sortDirection: props.sortDirection,
              sortKey: props.sortKey || undefined,
              onCellEdit: handleCellEdit,
              onPageChange: handlePageChange,
              onRowAction: handleRowAction,
              onSearchChange: handleSearchChange,
          });
  }
});

export const CindorEmptyState = defineComponent({
  name: "CindorEmptyState",
  setup(_, { attrs, slots }) {
    return () =>
          h(
            "cindor-empty-state",
            {
              ...attrs,
            },
            slots
          );
  }
});

export const CindorEmptySearchResults = defineComponent({
  name: "CindorEmptySearchResults",
  props: {
    description: { type: String, default: "" },
    heading: { type: String, default: "No matching results" },
    query: { type: String, default: "" }
  },
  setup(props, { attrs, slots }) {
    return () =>
          h(
            "cindor-empty-search-results",
            {
              ...attrs,
              description: props.description || undefined,
              heading: props.heading,
              query: props.query || undefined,
            },
            slots
          );
  }
});

export const CindorIcon = defineComponent({
  name: "CindorIcon",
  props: {
    label: { type: String, default: "" },
    name: { type: String, default: "" },
    size: { type: Number, default: 20 },
    strokeWidth: { type: Number, default: 2 }
  },
  setup(props, { attrs }) {
    return () =>
          h("cindor-icon", {
              ...attrs,
              label: props.label || undefined,
              name: props.name || undefined,
              size: props.size,
              strokeWidth: props.strokeWidth,
          });
  }
});

export const CindorCodeBlock = defineComponent({
  name: "CindorCodeBlock",
  props: {
    code: { type: String, default: "" },
    language: { type: String, default: "" }
  },
  setup(props, { attrs, slots }) {
    return () =>
          h(
            "cindor-code-block",
            {
              ...attrs,
              code: props.code || undefined,
              language: props.language || undefined,
            },
            slots.default?.()
          );
  }
});

export const CindorCommandBar = defineComponent({
  name: "CindorCommandBar",
  props: {
    count: { type: Number, default: 0 },
    countLabel: { type: String, default: "selected" },
    description: { type: String, default: "" },
    label: { type: String, default: "" },
    sticky: { type: Boolean, default: false }
  },
  setup(props, { attrs, slots }) {
    return () =>
          h(
            "cindor-command-bar",
            {
              ...attrs,
              count: props.count,
              "count-label": props.countLabel,
              description: props.description || undefined,
              label: props.label || undefined,
              sticky: props.sticky || undefined,
            },
            slots
          );
  }
});

export const CindorCommandPalette = defineComponent({
  name: "CindorCommandPalette",
  props: {
    commands: { type: Array as PropType<CommandPaletteCommand[]>, default: () => [] },
    emptyMessage: { type: String, default: "No matching commands." },
    modelValue: { type: String, default: "" },
    open: { type: Boolean, default: false },
    placeholder: { type: String, default: "Search commands" },
    query: { type: String, default: "" },
    title: { type: String, default: "Command palette" }
  },
  emits: ["update:modelValue", "input", "change", "update:open", "close", "cancel", "command-select"],
  setup(props, { attrs, emit }) {
    const handleInput = (event: Event) => {
      const target = event.currentTarget as InputHost;
      emit("update:modelValue", target.value);
      emit("input", event);
    };

    const handleChange = (event: Event) => {
      const target = event.currentTarget as InputHost;
      emit("update:modelValue", target.value);
      emit("change", event);
    };

    const handleClose = (event: Event) => {
      emit("update:open", false);
      emit("close", event);
    };

    const handleCancel = (event: Event) => {
      emit("update:open", false);
      emit("cancel", event);
    };

    const handleCommandSelect = (event: Event) => {
      emit("command-select", event);
    };
    return () =>
          h("cindor-command-palette", {
              ...attrs,
              commands: props.commands,
              "empty-message": props.emptyMessage,
              value: props.modelValue,
              open: props.open || undefined,
              placeholder: props.placeholder,
              query: props.query || undefined,
              title: props.title,
              onInput: handleInput,
              onChange: handleChange,
              onClose: handleClose,
              onCancel: handleCancel,
              onCommandSelect: handleCommandSelect,
          });
  }
});

export const CindorContextMenu = defineComponent({
  name: "CindorContextMenu",
  props: {
    open: { type: Boolean, default: false }
  },
  emits: ["update:open", "toggle"],
  setup(props, { attrs, emit, slots }) {
    const handleToggle = (event: Event) => {
      const target = event.currentTarget as OpenHost;
      emit("update:open", target.open);
      emit("toggle", event);
    };
    return () =>
          h(
            "cindor-context-menu",
            {
              ...attrs,
              open: props.open || undefined,
              onToggle: handleToggle,
            },
            slots
          );
  }
});

export const CindorDatePicker = defineComponent({
  name: "CindorDatePicker",
  props: {
    disabled: { type: Boolean, default: false },
    max: { type: String, default: "" },
    min: { type: String, default: "" },
    month: { type: String, default: "" },
    modelValue: { type: String, default: "" },
    name: { type: String, default: "" },
    open: { type: Boolean, default: false },
    placeholder: { type: String, default: "Select a date" },
    required: { type: Boolean, default: false }
  },
  emits: ["update:modelValue", "input", "change", "update:open", "toggle"],
  setup(props, { attrs, emit }) {
    const handleInput = (event: Event) => {
      const target = event.currentTarget as InputHost;
      emit("update:modelValue", target.value);
      emit("input", event);
    };

    const handleChange = (event: Event) => {
      const target = event.currentTarget as InputHost;
      emit("update:modelValue", target.value);
      emit("change", event);
    };

    const handleToggle = (event: Event) => {
      const target = event.currentTarget as OpenHost;
      emit("update:open", target.open);
      emit("toggle", event);
    };
    return () =>
          h("cindor-date-picker", {
              ...attrs,
              disabled: props.disabled || undefined,
              max: props.max || undefined,
              min: props.min || undefined,
              month: props.month || undefined,
              value: props.modelValue,
              name: props.name || undefined,
              open: props.open || undefined,
              placeholder: props.placeholder,
              required: props.required || undefined,
              onInput: handleInput,
              onChange: handleChange,
              onToggle: handleToggle,
          });
  }
});

export const CindorDateRangePicker = defineComponent({
  name: "CindorDateRangePicker",
  props: {
    endValue: { type: String, default: "" },
    max: { type: String, default: "" },
    min: { type: String, default: "" },
    month: { type: String, default: "" },
    open: { type: Boolean, default: false },
    placeholder: { type: String, default: "Select a date range" },
    startValue: { type: String, default: "" }
  },
  emits: ["input", "change", "update:open", "toggle"],
  setup(props, { attrs, emit }) {
    const handleInput = (event: Event) => {
      emit("input", event);
    };

    const handleChange = (event: Event) => {
      emit("change", event);
    };

    const handleToggle = (event: Event) => {
      const target = event.currentTarget as OpenHost;
      emit("update:open", target.open);
      emit("toggle", event);
    };
    return () =>
          h("cindor-date-range-picker", {
              ...attrs,
              "end-value": props.endValue || undefined,
              max: props.max || undefined,
              min: props.min || undefined,
              month: props.month || undefined,
              open: props.open || undefined,
              placeholder: props.placeholder,
              "start-value": props.startValue || undefined,
              onInput: handleInput,
              onChange: handleChange,
              onToggle: handleToggle,
          });
  }
});

export const CindorDateTimePicker = defineComponent({
  name: "CindorDateTimePicker",
  props: {
    dateValue: { type: String, default: "" },
    disabled: { type: Boolean, default: false },
    modelValue: { type: String, default: "" },
    name: { type: String, default: "" },
    required: { type: Boolean, default: false },
    timeValue: { type: String, default: "" }
  },
  emits: ["update:modelValue", "input", "change"],
  setup(props, { attrs, emit }) {
    const handleInput = (event: Event) => {
      const target = event.currentTarget as InputHost;
      emit("update:modelValue", target.value);
      emit("input", event);
    };

    const handleChange = (event: Event) => {
      const target = event.currentTarget as InputHost;
      emit("update:modelValue", target.value);
      emit("change", event);
    };
    return () =>
          h("cindor-date-time-picker", {
              ...attrs,
              "date-value": props.dateValue || undefined,
              disabled: props.disabled || undefined,
              value: props.modelValue,
              name: props.name || undefined,
              required: props.required || undefined,
              "time-value": props.timeValue || undefined,
              onInput: handleInput,
              onChange: handleChange,
          });
  }
});

export const CindorListbox = defineComponent({
  name: "CindorListbox",
  props: {
    activeIndex: { type: Number, default: -1 },
    multiselectable: { type: Boolean, default: false },
    selectedValue: { type: String, default: "" }
  },
  setup(props, { attrs, slots }) {
    return () =>
          h(
            "cindor-listbox",
            {
              ...attrs,
              activeIndex: props.activeIndex,
              multiselectable: props.multiselectable || undefined,
              selectedValue: props.selectedValue || undefined,
            },
            slots.default?.()
          );
  }
});

export const CindorDescriptionItem = defineComponent({
  name: "CindorDescriptionItem",
  setup(_, { attrs, slots }) {
    return () =>
          h(
            "cindor-description-item",
            {
              ...attrs,
            },
            slots
          );
  }
});

export const CindorDescriptionList = defineComponent({
  name: "CindorDescriptionList",
  setup(_, { attrs, slots }) {
    return () =>
          h(
            "cindor-description-list",
            {
              ...attrs,
            },
            slots.default?.()
          );
  }
});

export const CindorMenu = defineComponent({
  name: "CindorMenu",
  setup(_, { attrs, slots }) {
    return () =>
          h(
            "cindor-menu",
            {
              ...attrs,
            },
            slots.default?.()
          );
  }
});

export const CindorMenuItem = defineComponent({
  name: "CindorMenuItem",
  props: {
    disabled: { type: Boolean, default: false }
  },
  setup(props, { attrs, slots }) {
    return () =>
          h(
            "cindor-menu-item",
            {
              ...attrs,
              disabled: props.disabled || undefined,
            },
            slots.default?.()
          );
  }
});

export const CindorMultiSelect = defineComponent({
  name: "CindorMultiSelect",
  props: {
    disabled: { type: Boolean, default: false },
    name: { type: String, default: "" },
    open: { type: Boolean, default: false },
    placeholder: { type: String, default: "Select options" },
    required: { type: Boolean, default: false },
    modelValue: { type: Array as PropType<string[]>, default: () => [] }
  },
  emits: ["update:modelValue", "input", "change"],
  setup(props, { attrs, emit, slots }) {
    const handleInput = (event: Event) => {
      const target = event.currentTarget as HTMLElement & { values: string[] };
      emit("update:modelValue", target.values);
      emit("input", event);
    };

    const handleChange = (event: Event) => {
      const target = event.currentTarget as HTMLElement & { values: string[] };
      emit("update:modelValue", target.values);
      emit("change", event);
    };
    return () =>
          h(
            "cindor-multi-select",
            {
              ...attrs,
              disabled: props.disabled || undefined,
              name: props.name || undefined,
              open: props.open || undefined,
              placeholder: props.placeholder,
              required: props.required || undefined,
              values: props.modelValue,
              onInput: handleInput,
              onChange: handleChange,
            },
            slots.default?.()
          );
  }
});

export const CindorTagInput = defineComponent({
  name: "CindorTagInput",
  props: {
    disabled: { type: Boolean, default: false },
    name: { type: String, default: "" },
    placeholder: { type: String, default: "Add a tag" },
    required: { type: Boolean, default: false },
    modelValue: { type: Array as PropType<string[]>, default: () => [] }
  },
  emits: ["update:modelValue", "input", "change"],
  setup(props, { attrs, emit }) {
    const handleInput = (event: Event) => {
      const target = event.currentTarget as HTMLElement & { values: string[] };
      emit("update:modelValue", target.values);
      emit("input", event);
    };

    const handleChange = (event: Event) => {
      const target = event.currentTarget as HTMLElement & { values: string[] };
      emit("update:modelValue", target.values);
      emit("change", event);
    };
    return () =>
          h("cindor-tag-input", {
              ...attrs,
              disabled: props.disabled || undefined,
              name: props.name || undefined,
              placeholder: props.placeholder,
              required: props.required || undefined,
              values: props.modelValue,
              onInput: handleInput,
              onChange: handleChange,
          });
  }
});

export const CindorNumberInput = defineComponent({
  name: "CindorNumberInput",
  props: {
    disabled: { type: Boolean, default: false },
    modelValue: { type: String, default: "" },
    name: { type: String, default: "" },
    startIcon: { type: String, default: "" },
    endIcon: { type: String, default: "" },
    placeholder: { type: String, default: "" },
    readonly: { type: Boolean, default: false },
    required: { type: Boolean, default: false },
    max: { type: String, default: "" },
    min: { type: String, default: "" },
    step: { type: String, default: "" }
  },
  emits: ["update:modelValue", "input", "change"],
  setup(props, { attrs, emit }) {
    const handleInput = (event: Event) => {
      const target = event.currentTarget as InputHost;
      emit("update:modelValue", target.value);
      emit("input", event);
    };

    const handleChange = (event: Event) => {
      const target = event.currentTarget as InputHost;
      emit("update:modelValue", target.value);
      emit("change", event);
    };
    return () =>
          h("cindor-number-input", {
              ...attrs,
              disabled: props.disabled || undefined,
              value: props.modelValue,
              name: props.name || undefined,
              "start-icon": props.startIcon || undefined,
              "end-icon": props.endIcon || undefined,
              placeholder: props.placeholder || undefined,
              readonly: props.readonly || undefined,
              required: props.required || undefined,
              max: props.max || undefined,
              min: props.min || undefined,
              step: props.step || undefined,
              onInput: handleInput,
              onChange: handleChange,
          });
  }
});

export const CindorSearch = defineComponent({
  name: "CindorSearch",
  props: {
    autocomplete: { type: String, default: "" },
    disabled: { type: Boolean, default: false },
    modelValue: { type: String, default: "" },
    name: { type: String, default: "" },
    startIcon: { type: String, default: "search" },
    endIcon: { type: String, default: "" },
    placeholder: { type: String, default: "" },
    readonly: { type: Boolean, default: false },
    required: { type: Boolean, default: false }
  },
  emits: ["update:modelValue", "input", "change"],
  setup(props, { attrs, emit }) {
    const handleInput = (event: Event) => {
      const target = event.currentTarget as InputHost;
      emit("update:modelValue", target.value);
      emit("input", event);
    };

    const handleChange = (event: Event) => {
      const target = event.currentTarget as InputHost;
      emit("update:modelValue", target.value);
      emit("change", event);
    };
    return () =>
          h("cindor-search", {
              ...attrs,
              autocomplete: props.autocomplete || undefined,
              disabled: props.disabled || undefined,
              value: props.modelValue,
              name: props.name || undefined,
              "start-icon": props.startIcon,
              "end-icon": props.endIcon || undefined,
              placeholder: props.placeholder || undefined,
              readonly: props.readonly || undefined,
              required: props.required || undefined,
              onInput: handleInput,
              onChange: handleChange,
          });
  }
});

export const CindorSplitter = defineComponent({
  name: "CindorSplitter",
  props: {
    orientation: { type: String as PropType<SplitterOrientation>, default: "horizontal" }
  },
  emits: ["panel-resize"],
  setup(props, { attrs, emit, slots }) {
    const handlePanelResize = (event: Event) => {
      emit("panel-resize", event);
    };
    return () =>
          h(
            "cindor-splitter",
            {
              ...attrs,
              orientation: props.orientation,
              onPanelResize: handlePanelResize,
            },
            slots.default?.()
          );
  }
});

export const CindorSplitterPanel = defineComponent({
  name: "CindorSplitterPanel",
  props: {
    minSize: { type: Number, default: 10 },
    size: { type: Number, default: 0 }
  },
  setup(props, { attrs, slots }) {
    return () =>
          h(
            "cindor-splitter-panel",
            {
              ...attrs,
              "min-size": props.minSize,
              size: props.size,
            },
            slots.default?.()
          );
  }
});

export const CindorSegmentedControl = defineComponent({
  name: "CindorSegmentedControl",
  props: {
    disabled: { type: Boolean, default: false },
    modelValue: { type: String, default: "" },
    name: { type: String, default: "" },
    options: { type: Array as PropType<SegmentedControlOption[]>, default: () => [] },
    required: { type: Boolean, default: false }
  },
  emits: ["update:modelValue", "input", "change"],
  setup(props, { attrs, emit }) {
    const handleInput = (event: Event) => {
      const target = event.currentTarget as InputHost;
      emit("update:modelValue", target.value);
      emit("input", event);
    };

    const handleChange = (event: Event) => {
      const target = event.currentTarget as InputHost;
      emit("update:modelValue", target.value);
      emit("change", event);
    };
    return () =>
          h("cindor-segmented-control", {
              ...attrs,
              disabled: props.disabled || undefined,
              value: props.modelValue,
              name: props.name || undefined,
              options: props.options,
              required: props.required || undefined,
              onInput: handleInput,
              onChange: handleChange,
          });
  }
});

export const CindorCombobox = defineComponent({
  name: "CindorCombobox",
  props: {
    autocomplete: { type: String, default: "" },
    disabled: { type: Boolean, default: false },
    modelValue: { type: String, default: "" },
    name: { type: String, default: "" },
    placeholder: { type: String, default: "" },
    readonly: { type: Boolean, default: false },
    required: { type: Boolean, default: false }
  },
  emits: ["update:modelValue", "input", "change"],
  setup(props, { attrs, emit, slots }) {
    const handleInput = (event: Event) => {
      const target = event.currentTarget as InputHost;
      emit("update:modelValue", target.value);
      emit("input", event);
    };

    const handleChange = (event: Event) => {
      const target = event.currentTarget as InputHost;
      emit("update:modelValue", target.value);
      emit("change", event);
    };
    return () =>
          h(
            "cindor-combobox",
            {
              ...attrs,
              autocomplete: props.autocomplete || undefined,
              disabled: props.disabled || undefined,
              value: props.modelValue,
              name: props.name || undefined,
              placeholder: props.placeholder || undefined,
              readonly: props.readonly || undefined,
              required: props.required || undefined,
              onInput: handleInput,
              onChange: handleChange,
            },
            slots.default?.()
          );
  }
});

export const CindorDateInput = defineComponent({
  name: "CindorDateInput",
  props: {
    disabled: { type: Boolean, default: false },
    max: { type: String, default: "" },
    min: { type: String, default: "" },
    modelValue: { type: String, default: "" },
    name: { type: String, default: "" },
    startIcon: { type: String, default: "" },
    endIcon: { type: String, default: "" },
    readonly: { type: Boolean, default: false },
    required: { type: Boolean, default: false }
  },
  emits: ["update:modelValue", "input", "change"],
  setup(props, { attrs, emit }) {
    const handleInput = (event: Event) => {
      const target = event.currentTarget as InputHost;
      emit("update:modelValue", target.value);
      emit("input", event);
    };

    const handleChange = (event: Event) => {
      const target = event.currentTarget as InputHost;
      emit("update:modelValue", target.value);
      emit("change", event);
    };
    return () =>
          h("cindor-date-input", {
              ...attrs,
              disabled: props.disabled || undefined,
              max: props.max || undefined,
              min: props.min || undefined,
              value: props.modelValue,
              name: props.name || undefined,
              "start-icon": props.startIcon || undefined,
              "end-icon": props.endIcon || undefined,
              readonly: props.readonly || undefined,
              required: props.required || undefined,
              onInput: handleInput,
              onChange: handleChange,
          });
  }
});

export const CindorTimeInput = defineComponent({
  name: "CindorTimeInput",
  props: {
    disabled: { type: Boolean, default: false },
    max: { type: String, default: "" },
    min: { type: String, default: "" },
    modelValue: { type: String, default: "" },
    name: { type: String, default: "" },
    startIcon: { type: String, default: "" },
    endIcon: { type: String, default: "" },
    readonly: { type: Boolean, default: false },
    required: { type: Boolean, default: false },
    step: { type: String, default: "" }
  },
  emits: ["update:modelValue", "input", "change"],
  setup(props, { attrs, emit }) {
    const handleInput = (event: Event) => {
      const target = event.currentTarget as InputHost;
      emit("update:modelValue", target.value);
      emit("input", event);
    };

    const handleChange = (event: Event) => {
      const target = event.currentTarget as InputHost;
      emit("update:modelValue", target.value);
      emit("change", event);
    };
    return () =>
          h("cindor-time-input", {
              ...attrs,
              disabled: props.disabled || undefined,
              max: props.max || undefined,
              min: props.min || undefined,
              value: props.modelValue,
              name: props.name || undefined,
              "start-icon": props.startIcon || undefined,
              "end-icon": props.endIcon || undefined,
              readonly: props.readonly || undefined,
              required: props.required || undefined,
              step: props.step || undefined,
              onInput: handleInput,
              onChange: handleChange,
          });
  }
});

export const CindorRatingInput = defineComponent({
  name: "CindorRatingInput",
  props: {
    clearable: { type: Boolean, default: false },
    disabled: { type: Boolean, default: false },
    max: { type: Number, default: 5 },
    modelValue: { type: Number, default: 0 },
    name: { type: String, default: "" },
    required: { type: Boolean, default: false }
  },
  emits: ["update:modelValue", "input", "change"],
  setup(props, { attrs, emit }) {
    const handleInput = (event: Event) => {
      const target = event.currentTarget as InputHost;
      emit("update:modelValue", Number(target.value));
      emit("input", event);
    };

    const handleChange = (event: Event) => {
      const target = event.currentTarget as InputHost;
      emit("update:modelValue", Number(target.value));
      emit("change", event);
    };
    return () =>
          h("cindor-rating-input", {
              ...attrs,
              clearable: props.clearable || undefined,
              disabled: props.disabled || undefined,
              max: props.max,
              value: props.modelValue,
              name: props.name || undefined,
              required: props.required || undefined,
              onInput: handleInput,
              onChange: handleChange,
          });
  }
});

export const CindorToast = defineComponent({
  name: "CindorToast",
  props: {
    dismissible: { type: Boolean, default: false },
    open: { type: Boolean, default: true },
    tone: { type: String as PropType<"neutral" | "success" | "warning" | "danger">, default: "neutral" }
  },
  emits: ["update:open", "close"],
  setup(props, { attrs, emit, slots }) {
    const handleClose = (event: Event) => {
      emit("update:open", false);
      emit("close", event);
    };
    return () =>
          h(
            "cindor-toast",
            {
              ...attrs,
              dismissible: props.dismissible || undefined,
              open: props.open || undefined,
              tone: props.tone,
              onClose: handleClose,
            },
            slots.default?.()
          );
  }
});

export const CindorToastRegion = defineComponent({
  name: "CindorToastRegion",
  props: {
    maxVisible: { type: Number, default: 5 },
    placement: { type: String as PropType<ToastPlacement>, default: "top-end" }
  },
  emits: ["toast-show", "toast-remove"],
  setup(props, { attrs, emit, slots }) {
    const handleToastShow = (event: Event) => {
      emit("toast-show", event);
    };

    const handleToastRemove = (event: Event) => {
      emit("toast-remove", event);
    };
    return () =>
          h(
            "cindor-toast-region",
            {
              ...attrs,
              maxVisible: props.maxVisible,
              placement: props.placement,
              onToastShow: handleToastShow,
              onToastRemove: handleToastRemove,
            },
            slots
          );
  }
});

export const CindorTooltip = defineComponent({
  name: "CindorTooltip",
  props: {
    open: { type: Boolean, default: false },
    text: { type: String, default: "" }
  },
  setup(props, { attrs, slots }) {
    return () =>
          h(
            "cindor-tooltip",
            {
              ...attrs,
              open: props.open || undefined,
              text: props.text || undefined,
            },
            slots.default?.()
          );
  }
});

export const CindorToolbar = defineComponent({
  name: "CindorToolbar",
  props: {
    orientation: { type: String as PropType<ToolbarOrientation>, default: "horizontal" },
    wrap: { type: Boolean, default: false }
  },
  setup(props, { attrs, slots }) {
    return () =>
          h(
            "cindor-toolbar",
            {
              ...attrs,
              orientation: props.orientation,
              wrap: props.wrap || undefined,
            },
            slots.default?.()
          );
  }
});

export const CindorPopover = defineComponent({
  name: "CindorPopover",
  props: {
    open: { type: Boolean, default: false }
  },
  emits: ["update:open", "toggle"],
  setup(props, { attrs, emit, slots }) {
    const handleToggle = (event: Event) => {
      const target = event.currentTarget as OpenHost;
      emit("update:open", target.open);
      emit("toggle", event);
    };
    return () =>
          h(
            "cindor-popover",
            {
              ...attrs,
              open: props.open || undefined,
              onToggle: handleToggle,
            },
            slots.default?.()
          );
  }
});

export const CindorDropdownMenu = defineComponent({
  name: "CindorDropdownMenu",
  props: {
    open: { type: Boolean, default: false }
  },
  emits: ["update:open", "toggle"],
  setup(props, { attrs, emit, slots }) {
    const handleToggle = (event: Event) => {
      const target = event.currentTarget as OpenHost;
      emit("update:open", target.open);
      emit("toggle", event);
    };
    return () =>
          h(
            "cindor-dropdown-menu",
            {
              ...attrs,
              open: props.open || undefined,
              onToggle: handleToggle,
            },
            slots.default?.()
          );
  }
});

export const CindorDropzone = defineComponent({
  name: "CindorDropzone",
  props: {
    accept: { type: String, default: "" },
    disabled: { type: Boolean, default: false },
    multiple: { type: Boolean, default: false },
    name: { type: String, default: "" },
    required: { type: Boolean, default: false }
  },
  emits: ["update:files", "input", "change"],
  setup(props, { attrs, emit }) {
    const handleInput = (event: Event) => {
      const target = event.currentTarget as FileInputHost;
      emit("update:files", target.files);
      emit("input", event);
    };

    const handleChange = (event: Event) => {
      const target = event.currentTarget as FileInputHost;
      emit("update:files", target.files);
      emit("change", event);
    };
    return () =>
          h("cindor-dropzone", {
              ...attrs,
              accept: props.accept || undefined,
              disabled: props.disabled || undefined,
              multiple: props.multiple || undefined,
              name: props.name || undefined,
              required: props.required || undefined,
              onInput: handleInput,
              onChange: handleChange,
          });
  }
});

export const CindorDrawer = defineComponent({
  name: "CindorDrawer",
  props: {
    open: { type: Boolean, default: false },
    side: { type: String as PropType<"start" | "end">, default: "end" }
  },
  emits: ["update:open", "close"],
  setup(props, { attrs, emit, slots }) {
    const handleClose = (event: Event) => {
      emit("update:open", false);
      emit("close", event);
    };
    return () =>
          h(
            "cindor-drawer",
            {
              ...attrs,
              open: props.open || undefined,
              side: props.side,
              onClose: handleClose,
            },
            slots.default?.()
          );
  }
});

export const CindorInput = defineComponent({
  name: "CindorInput",
  props: {
    autocomplete: { type: String, default: "" },
    disabled: { type: Boolean, default: false },
    modelValue: { type: String, default: "" },
    name: { type: String, default: "" },
    startIcon: { type: String, default: "" },
    endIcon: { type: String, default: "" },
    placeholder: { type: String, default: "" },
    readonly: { type: Boolean, default: false },
    required: { type: Boolean, default: false },
    type: { type: String, default: "text" }
  },
  emits: ["update:modelValue", "input", "change"],
  setup(props, { attrs, emit }) {
    const handleInput = (event: Event) => {
      const target = event.currentTarget as InputHost;
      emit("update:modelValue", target.value);
      emit("input", event);
    };

    const handleChange = (event: Event) => {
      const target = event.currentTarget as InputHost;
      emit("update:modelValue", target.value);
      emit("change", event);
    };
    return () =>
          h("cindor-input", {
              ...attrs,
              autocomplete: props.autocomplete || undefined,
              disabled: props.disabled || undefined,
              value: props.modelValue,
              name: props.name || undefined,
              "start-icon": props.startIcon || undefined,
              "end-icon": props.endIcon || undefined,
              placeholder: props.placeholder || undefined,
              readonly: props.readonly || undefined,
              required: props.required || undefined,
              type: props.type,
              onInput: handleInput,
              onChange: handleChange,
          });
  }
});

export const CindorInlineEdit = defineComponent({
  name: "CindorInlineEdit",
  props: {
    disabled: { type: Boolean, default: false },
    editing: { type: Boolean, default: false },
    modelValue: { type: String, default: "" },
    placeholder: { type: String, default: "Click edit" }
  },
  emits: ["update:modelValue", "input", "change", "cancel", "update:editing", "toggle"],
  setup(props, { attrs, emit }) {
    const handleInput = (event: Event) => {
      const target = event.currentTarget as InputHost;
      emit("update:modelValue", target.value);
      emit("input", event);
    };

    const handleChange = (event: Event) => {
      const target = event.currentTarget as InputHost;
      emit("update:modelValue", target.value);
      emit("change", event);
    };

    const handleCancel = (event: Event) => {
      emit("cancel", event);
    };

    const handleToggle = (event: Event) => {
      const target = event.currentTarget as HTMLElement & { editing: boolean };
      emit("update:editing", target.editing);
      emit("toggle", event);
    };
    return () =>
          h("cindor-inline-edit", {
              ...attrs,
              disabled: props.disabled || undefined,
              editing: props.editing || undefined,
              value: props.modelValue,
              placeholder: props.placeholder,
              onInput: handleInput,
              onChange: handleChange,
              onCancel: handleCancel,
              onToggle: handleToggle,
          });
  }
});

export const CindorLayout = defineComponent({
  name: "CindorLayout",
  setup(_, { attrs, slots }) {
    return () =>
          h(
            "cindor-layout",
            {
              ...attrs,
            },
            slots.default?.()
          );
  }
});

export const CindorLayoutContent = defineComponent({
  name: "CindorLayoutContent",
  setup(_, { attrs, slots }) {
    return () =>
          h(
            "cindor-layout-content",
            {
              ...attrs,
            },
            slots.default?.()
          );
  }
});

export const CindorLayoutHeader = defineComponent({
  name: "CindorLayoutHeader",
  setup(_, { attrs, slots }) {
    return () =>
          h(
            "cindor-layout-header",
            {
              ...attrs,
            },
            slots.default?.()
          );
  }
});

export const CindorEmailInput = defineComponent({
  name: "CindorEmailInput",
  props: {
    autocomplete: { type: String, default: "email" },
    disabled: { type: Boolean, default: false },
    modelValue: { type: String, default: "" },
    name: { type: String, default: "" },
    startIcon: { type: String, default: "" },
    endIcon: { type: String, default: "" },
    placeholder: { type: String, default: "" },
    readonly: { type: Boolean, default: false },
    required: { type: Boolean, default: false }
  },
  emits: ["update:modelValue", "input", "change"],
  setup(props, { attrs, emit }) {
    const handleInput = (event: Event) => {
      const target = event.currentTarget as InputHost;
      emit("update:modelValue", target.value);
      emit("input", event);
    };

    const handleChange = (event: Event) => {
      const target = event.currentTarget as InputHost;
      emit("update:modelValue", target.value);
      emit("change", event);
    };
    return () =>
          h("cindor-email-input", {
              ...attrs,
              autocomplete: props.autocomplete,
              disabled: props.disabled || undefined,
              value: props.modelValue,
              name: props.name || undefined,
              "start-icon": props.startIcon || undefined,
              "end-icon": props.endIcon || undefined,
              placeholder: props.placeholder || undefined,
              readonly: props.readonly || undefined,
              required: props.required || undefined,
              onInput: handleInput,
              onChange: handleChange,
          });
  }
});

export const CindorPasswordInput = defineComponent({
  name: "CindorPasswordInput",
  props: {
    autocomplete: { type: String, default: "current-password" },
    disabled: { type: Boolean, default: false },
    modelValue: { type: String, default: "" },
    name: { type: String, default: "" },
    placeholder: { type: String, default: "" },
    readonly: { type: Boolean, default: false },
    required: { type: Boolean, default: false }
  },
  emits: ["update:modelValue", "input", "change"],
  setup(props, { attrs, emit }) {
    const handleInput = (event: Event) => {
      const target = event.currentTarget as InputHost;
      emit("update:modelValue", target.value);
      emit("input", event);
    };

    const handleChange = (event: Event) => {
      const target = event.currentTarget as InputHost;
      emit("update:modelValue", target.value);
      emit("change", event);
    };
    return () =>
          h("cindor-password-input", {
              ...attrs,
              autocomplete: props.autocomplete,
              disabled: props.disabled || undefined,
              value: props.modelValue,
              name: props.name || undefined,
              placeholder: props.placeholder || undefined,
              readonly: props.readonly || undefined,
              required: props.required || undefined,
              onInput: handleInput,
              onChange: handleChange,
          });
  }
});

export const CindorOption = defineComponent({
  name: "CindorOption",
  props: {
    active: { type: Boolean, default: false },
    disabled: { type: Boolean, default: false },
    label: { type: String, default: "" },
    selected: { type: Boolean, default: false },
    value: { type: String, default: "" }
  },
  setup(props, { attrs, slots }) {
    return () =>
          h(
            "cindor-option",
            {
              ...attrs,
              active: props.active || undefined,
              disabled: props.disabled || undefined,
              label: props.label || undefined,
              selected: props.selected || undefined,
              value: props.value || undefined,
            },
            slots.default?.()
          );
  }
});

export const CindorMenubar = defineComponent({
  name: "CindorMenubar",
  setup(_, { attrs, slots }) {
    return () =>
          h(
            "cindor-menubar",
            {
              ...attrs,
            },
            slots.default?.()
          );
  }
});

export const CindorNavigationRail = defineComponent({
  name: "CindorNavigationRail",
  setup(_, { attrs, slots }) {
    return () =>
          h(
            "cindor-navigation-rail",
            {
              ...attrs,
            },
            slots.default?.()
          );
  }
});

export const CindorNavigationRailItem = defineComponent({
  name: "CindorNavigationRailItem",
  props: {
    current: { type: Boolean, default: false },
    disabled: { type: Boolean, default: false },
    href: { type: String, default: "" },
    label: { type: String, default: "" },
    rel: { type: String, default: "" },
    target: { type: String, default: "" },
    value: { type: String, default: "" }
  },
  setup(props, { attrs, slots }) {
    return () =>
          h(
            "cindor-navigation-rail-item",
            {
              ...attrs,
              current: props.current || undefined,
              disabled: props.disabled || undefined,
              href: props.href || undefined,
              label: props.label || undefined,
              rel: props.rel || undefined,
              target: props.target || undefined,
              value: props.value || undefined,
            },
            slots
          );
  }
});

export const CindorTelInput = defineComponent({
  name: "CindorTelInput",
  props: {
    autocomplete: { type: String, default: "tel" },
    disabled: { type: Boolean, default: false },
    modelValue: { type: String, default: "" },
    name: { type: String, default: "" },
    startIcon: { type: String, default: "" },
    endIcon: { type: String, default: "" },
    placeholder: { type: String, default: "" },
    readonly: { type: Boolean, default: false },
    required: { type: Boolean, default: false }
  },
  emits: ["update:modelValue", "input", "change"],
  setup(props, { attrs, emit }) {
    const handleInput = (event: Event) => {
      const target = event.currentTarget as InputHost;
      emit("update:modelValue", target.value);
      emit("input", event);
    };

    const handleChange = (event: Event) => {
      const target = event.currentTarget as InputHost;
      emit("update:modelValue", target.value);
      emit("change", event);
    };
    return () =>
          h("cindor-tel-input", {
              ...attrs,
              autocomplete: props.autocomplete,
              disabled: props.disabled || undefined,
              value: props.modelValue,
              name: props.name || undefined,
              "start-icon": props.startIcon || undefined,
              "end-icon": props.endIcon || undefined,
              placeholder: props.placeholder || undefined,
              readonly: props.readonly || undefined,
              required: props.required || undefined,
              onInput: handleInput,
              onChange: handleChange,
          });
  }
});

export const CindorUrlInput = defineComponent({
  name: "CindorUrlInput",
  props: {
    autocomplete: { type: String, default: "url" },
    disabled: { type: Boolean, default: false },
    modelValue: { type: String, default: "" },
    name: { type: String, default: "" },
    startIcon: { type: String, default: "" },
    endIcon: { type: String, default: "" },
    placeholder: { type: String, default: "" },
    readonly: { type: Boolean, default: false },
    required: { type: Boolean, default: false }
  },
  emits: ["update:modelValue", "input", "change"],
  setup(props, { attrs, emit }) {
    const handleInput = (event: Event) => {
      const target = event.currentTarget as InputHost;
      emit("update:modelValue", target.value);
      emit("input", event);
    };

    const handleChange = (event: Event) => {
      const target = event.currentTarget as InputHost;
      emit("update:modelValue", target.value);
      emit("change", event);
    };
    return () =>
          h("cindor-url-input", {
              ...attrs,
              autocomplete: props.autocomplete,
              disabled: props.disabled || undefined,
              value: props.modelValue,
              name: props.name || undefined,
              "start-icon": props.startIcon || undefined,
              "end-icon": props.endIcon || undefined,
              placeholder: props.placeholder || undefined,
              readonly: props.readonly || undefined,
              required: props.required || undefined,
              onInput: handleInput,
              onChange: handleChange,
          });
  }
});

export const CindorColorInput = defineComponent({
  name: "CindorColorInput",
  props: {
    disabled: { type: Boolean, default: false },
    modelValue: { type: String, default: "#4f46e5" },
    name: { type: String, default: "" }
  },
  emits: ["update:modelValue", "input", "change"],
  setup(props, { attrs, emit }) {
    const handleInput = (event: Event) => {
      const target = event.currentTarget as InputHost;
      emit("update:modelValue", target.value);
      emit("input", event);
    };

    const handleChange = (event: Event) => {
      const target = event.currentTarget as InputHost;
      emit("update:modelValue", target.value);
      emit("change", event);
    };
    return () =>
          h("cindor-color-input", {
              ...attrs,
              disabled: props.disabled || undefined,
              value: props.modelValue,
              name: props.name || undefined,
              onInput: handleInput,
              onChange: handleChange,
          });
  }
});

export const CindorCheckbox = defineComponent({
  name: "CindorCheckbox",
  props: {
    modelValue: { type: Boolean, default: false },
    disabled: { type: Boolean, default: false },
    name: { type: String, default: "" },
    required: { type: Boolean, default: false },
    value: { type: String, default: "on" }
  },
  emits: ["update:modelValue", "input", "change"],
  setup(props, { attrs, emit, slots }) {
    const handleInput = (event: Event) => {
      const target = event.currentTarget as CheckboxHost;
      emit("update:modelValue", target.checked);
      emit("input", event);
    };

    const handleChange = (event: Event) => {
      const target = event.currentTarget as CheckboxHost;
      emit("update:modelValue", target.checked);
      emit("change", event);
    };
    return () =>
          h(
            "cindor-checkbox",
            {
              ...attrs,
              checked: props.modelValue || undefined,
              disabled: props.disabled || undefined,
              name: props.name || undefined,
              required: props.required || undefined,
              value: props.value,
              onInput: handleInput,
              onChange: handleChange,
            },
            slots.default?.()
          );
  }
});

export const CindorSelect = defineComponent({
  name: "CindorSelect",
  props: {
    disabled: { type: Boolean, default: false },
    modelValue: { type: String, default: "" },
    name: { type: String, default: "" },
    required: { type: Boolean, default: false }
  },
  emits: ["update:modelValue", "input", "change"],
  setup(props, { attrs, emit, slots }) {
    const handleInput = (event: Event) => {
      const target = event.currentTarget as SelectHost;
      emit("update:modelValue", target.value);
      emit("input", event);
    };

    const handleChange = (event: Event) => {
      const target = event.currentTarget as SelectHost;
      emit("update:modelValue", target.value);
      emit("change", event);
    };
    return () =>
          h(
            "cindor-select",
            {
              ...attrs,
              disabled: props.disabled || undefined,
              value: props.modelValue,
              name: props.name || undefined,
              required: props.required || undefined,
              onInput: handleInput,
              onChange: handleChange,
            },
            slots.default?.()
          );
  }
});

export const CindorStack = defineComponent({
  name: "CindorStack",
  props: {
    align: { type: String as PropType<StackAlign>, default: "stretch" },
    direction: { type: String as PropType<StackDirection>, default: "vertical" },
    gap: { type: String as PropType<StackGap>, default: "3" },
    justify: { type: String as PropType<StackJustify>, default: "start" },
    wrap: { type: Boolean, default: false }
  },
  setup(props, { attrs, slots }) {
    return () =>
          h(
            "cindor-stack",
            {
              ...attrs,
              align: props.align,
              direction: props.direction,
              gap: props.gap,
              justify: props.justify,
              wrap: props.wrap || undefined,
            },
            slots.default?.()
          );
  }
});

export const CindorRadio = defineComponent({
  name: "CindorRadio",
  props: {
    checked: { type: Boolean, default: false },
    disabled: { type: Boolean, default: false },
    name: { type: String, default: "" },
    required: { type: Boolean, default: false },
    value: { type: String, default: "on" }
  },
  emits: ["update:checked", "input", "change"],
  setup(props, { attrs, emit, slots }) {
    const handleInput = (event: Event) => {
      const target = event.currentTarget as CheckboxHost;
      emit("update:checked", target.checked);
      emit("input", event);
    };

    const handleChange = (event: Event) => {
      const target = event.currentTarget as CheckboxHost;
      emit("update:checked", target.checked);
      emit("change", event);
    };
    return () =>
          h(
            "cindor-radio",
            {
              ...attrs,
              checked: props.checked || undefined,
              disabled: props.disabled || undefined,
              name: props.name || undefined,
              required: props.required || undefined,
              value: props.value,
              onInput: handleInput,
              onChange: handleChange,
            },
            slots.default?.()
          );
  }
});

export const CindorDialog = defineComponent({
  name: "CindorDialog",
  props: {
    modal: { type: Boolean, default: true },
    open: { type: Boolean, default: false }
  },
  emits: ["update:open", "close", "cancel"],
  setup(props, { attrs, emit, slots }) {
    const handleClose = (event: Event) => {
      emit("update:open", false);
      emit("close", event);
    };

    const handleCancel = (event: Event) => {
      emit("update:open", false);
      emit("cancel", event);
    };
    return () =>
          h(
            "cindor-dialog",
            {
              ...attrs,
              modal: props.modal || undefined,
              open: props.open || undefined,
              onClose: handleClose,
              onCancel: handleCancel,
            },
            slots.default?.()
          );
  }
});

export const CindorTextarea = defineComponent({
  name: "CindorTextarea",
  props: {
    disabled: { type: Boolean, default: false },
    modelValue: { type: String, default: "" },
    name: { type: String, default: "" },
    placeholder: { type: String, default: "" },
    readonly: { type: Boolean, default: false },
    required: { type: Boolean, default: false },
    rows: { type: Number, default: 4 }
  },
  emits: ["update:modelValue", "input", "change"],
  setup(props, { attrs, emit }) {
    const handleInput = (event: Event) => {
      const target = event.currentTarget as InputHost;
      emit("update:modelValue", target.value);
      emit("input", event);
    };

    const handleChange = (event: Event) => {
      const target = event.currentTarget as InputHost;
      emit("update:modelValue", target.value);
      emit("change", event);
    };
    return () =>
          h("cindor-textarea", {
              ...attrs,
              disabled: props.disabled || undefined,
              value: props.modelValue,
              name: props.name || undefined,
              placeholder: props.placeholder || undefined,
              readonly: props.readonly || undefined,
              required: props.required || undefined,
              rows: props.rows,
              onInput: handleInput,
              onChange: handleChange,
          });
  }
});

export const CindorSwitch = defineComponent({
  name: "CindorSwitch",
  props: {
    disabled: { type: Boolean, default: false },
    modelValue: { type: Boolean, default: false },
    name: { type: String, default: "" },
    required: { type: Boolean, default: false },
    value: { type: String, default: "on" }
  },
  emits: ["update:modelValue", "input", "change"],
  setup(props, { attrs, emit, slots }) {
    const handleInput = (event: Event) => {
      const target = event.currentTarget as CheckboxHost;
      emit("update:modelValue", target.checked);
      emit("input", event);
    };

    const handleChange = (event: Event) => {
      const target = event.currentTarget as CheckboxHost;
      emit("update:modelValue", target.checked);
      emit("change", event);
    };
    return () =>
          h(
            "cindor-switch",
            {
              ...attrs,
              disabled: props.disabled || undefined,
              checked: props.modelValue || undefined,
              name: props.name || undefined,
              required: props.required || undefined,
              value: props.value,
              onInput: handleInput,
              onChange: handleChange,
            },
            slots.default?.()
          );
  }
});

export const CindorTabPanel = defineComponent({
  name: "CindorTabPanel",
  props: {
    label: { type: String, default: "" },
    value: { type: String, default: "" }
  },
  setup(props, { attrs, slots }) {
    return () =>
          h(
            "cindor-tab-panel",
            {
              ...attrs,
              label: props.label || undefined,
              value: props.value || undefined,
            },
            slots.default?.()
          );
  }
});

export const CindorTabs = defineComponent({
  name: "CindorTabs",
  props: {
    value: { type: String, default: "" }
  },
  emits: ["update:value", "change"],
  setup(props, { attrs, emit, slots }) {
    const handleChange = (event: Event) => {
      const target = event.currentTarget as SelectHost;
      emit("update:value", target.value);
      emit("change", event);
    };
    return () =>
          h(
            "cindor-tabs",
            {
              ...attrs,
              value: props.value || undefined,
              onChange: handleChange,
            },
            slots.default?.()
          );
  }
});

export const CindorAccordion = defineComponent({
  name: "CindorAccordion",
  props: {
    open: { type: Boolean, default: false }
  },
  emits: ["update:open", "toggle"],
  setup(props, { attrs, emit, slots }) {
    const handleToggle = (event: Event) => {
      const target = event.currentTarget as OpenHost;
      emit("update:open", target.open);
      emit("toggle", event);
    };
    return () =>
          h(
            "cindor-accordion",
            {
              ...attrs,
              open: props.open || undefined,
              onToggle: handleToggle,
            },
            slots.default?.()
          );
  }
});

export const CindorTreeItem = defineComponent({
  name: "CindorTreeItem",
  props: {
    disabled: { type: Boolean, default: false },
    expanded: { type: Boolean, default: false },
    label: { type: String, default: "" },
    selected: { type: Boolean, default: false },
    value: { type: String, default: "" }
  },
  setup(props, { attrs, slots }) {
    return () =>
          h(
            "cindor-tree-item",
            {
              ...attrs,
              disabled: props.disabled || undefined,
              expanded: props.expanded || undefined,
              label: props.label || undefined,
              selected: props.selected || undefined,
              value: props.value || undefined,
            },
            slots
          );
  }
});

export const CindorTreeView = defineComponent({
  name: "CindorTreeView",
  props: {
    modelValue: { type: String, default: "" }
  },
  emits: ["update:modelValue", "input", "change"],
  setup(props, { attrs, emit, slots }) {
    const handleInput = (event: Event) => {
      const target = event.currentTarget as InputHost;
      emit("update:modelValue", target.value);
      emit("input", event);
    };

    const handleChange = (event: Event) => {
      const target = event.currentTarget as InputHost;
      emit("update:modelValue", target.value);
      emit("change", event);
    };
    return () =>
          h(
            "cindor-tree-view",
            {
              ...attrs,
              value: props.modelValue,
              onInput: handleInput,
              onChange: handleChange,
            },
            slots.default?.()
          );
  }
});

export const CindorStatCard = defineComponent({
  name: "CindorStatCard",
  props: {
    change: { type: String, default: "" },
    label: { type: String, default: "" },
    tone: { type: String as PropType<StatCardTone>, default: "neutral" },
    value: { type: String, default: "" }
  },
  setup(props, { attrs, slots }) {
    return () =>
          h(
            "cindor-stat-card",
            {
              ...attrs,
              change: props.change || undefined,
              label: props.label || undefined,
              tone: props.tone,
              value: props.value || undefined,
            },
            slots.default?.()
          );
  }
});

export const CindorTimeline = defineComponent({
  name: "CindorTimeline",
  setup(_, { attrs, slots }) {
    return () =>
          h(
            "cindor-timeline",
            {
              ...attrs,
            },
            slots.default?.()
          );
  }
});

export const CindorTimelineItem = defineComponent({
  name: "CindorTimelineItem",
  setup(_, { attrs, slots }) {
    return () =>
          h(
            "cindor-timeline-item",
            {
              ...attrs,
            },
            slots
          );
  }
});

export const CindorTransferList = defineComponent({
  name: "CindorTransferList",
  props: {
    availableLabel: { type: String, default: "Available" },
    disabled: { type: Boolean, default: false },
    name: { type: String, default: "" },
    required: { type: Boolean, default: false },
    selectedLabel: { type: String, default: "Selected" },
    modelValue: { type: Array as PropType<string[]>, default: () => [] },
    size: { type: Number, default: 8 }
  },
  emits: ["update:modelValue", "input", "change"],
  setup(props, { attrs, emit, slots }) {
    const handleInput = (event: Event) => {
      const target = event.currentTarget as HTMLElement & { selectedValues: string[] };
      emit("update:modelValue", target.selectedValues);
      emit("input", event);
    };

    const handleChange = (event: Event) => {
      const target = event.currentTarget as HTMLElement & { selectedValues: string[] };
      emit("update:modelValue", target.selectedValues);
      emit("change", event);
    };
    return () =>
          h(
            "cindor-transfer-list",
            {
              ...attrs,
              "available-label": props.availableLabel,
              disabled: props.disabled || undefined,
              name: props.name || undefined,
              required: props.required || undefined,
              "selected-label": props.selectedLabel,
              "selected-values": props.modelValue,
              size: props.size,
              onInput: handleInput,
              onChange: handleChange,
            },
            slots.default?.()
          );
  }
});

export const CindorSideNav = defineComponent({
  name: "CindorSideNav",
  setup(_, { attrs, slots }) {
    return () =>
          h(
            "cindor-side-nav",
            {
              ...attrs,
            },
            slots.default?.()
          );
  }
});

export const CindorSideNavItem = defineComponent({
  name: "CindorSideNavItem",
  props: {
    current: { type: Boolean, default: false },
    disabled: { type: Boolean, default: false },
    expanded: { type: Boolean, default: false },
    href: { type: String, default: "" },
    label: { type: String, default: "" },
    rel: { type: String, default: "" },
    target: { type: String, default: "" },
    value: { type: String, default: "" }
  },
  setup(props, { attrs, slots }) {
    return () =>
          h(
            "cindor-side-nav-item",
            {
              ...attrs,
              current: props.current || undefined,
              disabled: props.disabled || undefined,
              expanded: props.expanded || undefined,
              href: props.href || undefined,
              label: props.label || undefined,
              rel: props.rel || undefined,
              target: props.target || undefined,
              value: props.value || undefined,
            },
            slots
          );
  }
});
